alias w:= work
work day part:
    cargo watch -w day-{{ day }} -x "check -p day-{{ day }}" -s "just test {{ day }} {{ part }} " -s "just lint {{ day }}"

trace day part:
    RUST_LOG=info cargo watch -w day-{{ day }} -x "check -p day-{{ day }}" -s "just test day-{{ day }} part{{ part }} " -s "just lint day-{{ day }}"

lint day:
    cargo clippy -p day-{{ day }}

test day part:
    cargo nextest run -p day-{{ day }} part{{ part }}

bench-all:
    cargo bench -q > benchmarks.txt

bench day part:
    cargo bench --bench day-{{ day }} part{{ part }} >> day-{{ day }}.bench.txt

flamegraph day part:
    cargo flamegraph --profile flamegraph --root --package day-{{ day }} --bin part{{ part }} -o flamegraphs/day-{{ day }}--part{{ part }}.svg

dhat day part:
    cargo run --profile dhat --features dhat-heap --package day-{{ day }} --bin part{{ part }}

create day:
    cargo generate --path ./daily-template --name day-{{ day }}
    aoc d --day {{ day }} -p day-{{ day }}/puzzle.md -i day-{{ day }}/input1.txt
    cp day-{{ day }}/input1.txt day-{{ day }}/input2.txt
