work day part:
    cargo watch -x "check -p {{ day }}" -s "just test {{ day }} {{ part }} " -s "just lint {{ day }}"

lint day:
    clippy-tracing --action check --exclude target --exclude benches --exclude www
    cargo clippy -p {{ day }}

test day part:
    cargo nextest run {{ day }} {{ part }}

bench-all:
    cargo bench -q > benchmarks.txt

bench day part:
    cargo bench --bench {{ day }} {{ part }} >> {{ day }}.bench.txt

flamegraph day part:
    cargo flamegraph --profile flamegraph --root --package {{ day }} --bin {{ part }} -o flamegraphs/{{ day }}--{{ part }}.svg

dhat day part:
    cargo run --profile dhat --features dhat-heap --package {{ day }} --bin {{ part }}

create day:
    cargo generate --path ./daily-template --name day-{{ day }}
    aoc d --day {{ day }} -p day-{{ day }}/puzzle.md -i day-{{ day }}/input1.txt
    cp day-{{ day }}/input1.txt day-{{ day }}/input2.txt
